# theme: minimal-mistakes-jekyll

# Site Settings
locale                   : "en-US"
title                    : "Heatapy"
title_separator          : "-"
subtitle                 : "Python framework for Computing transient heat transfer processes"
name                     : "Heatrapy project"
description              : "Python framework for Computing transient heat transfer processes."
logo_path                : "/assets/heatrapy.png"
url                      : "https://djsilva99.github.io/heatrapy"

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url:

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


remote_theme: "mmistakes/minimal-mistakes@gh-pages"
