# Site Settings
locale                   : "en-US"
title                    : "Heatapy"
title_separator          : "-"
subtitle                 : "Python framework for computing transient heat transfer processes"
name                     : "Heatrapy project"
description              : "Python framework for computing transient heat transfer processes."
logo_path                : "/assets/heatrapy.png"

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"

# Plugins (previously gems:)
plugins:
  - jekyll-include-cache


remote_theme: "mmistakes/minimal-mistakes@4.17.2"
